### ISSUE TITLE
Block doesn't render Wordpress version 5.0.3

### ISSUE THREAD

**Issue by Niels-P** [MWDelaney/sage-acf-gutenberg-blocks#1]
Hi MWDelaney,

I'm having an issue with this library. It created a directory where I can place my block. I followed your testimonial example, and it gets displayed as an option within the Gutenberg editor.

I've attached ACF fields to the block, and those are shown as well. However, when I enter preview mode / go to the page where the block is supposed to be, it's blank. It seems like it doesn't render. Any idea what I might have done wrong? I followed each step you've suggested.

Kind regards,
Niels

**Comment by MWDelaney** [comment]
Can you try entering some static content in the block template and seeing if that renders in the preview? That would narrow down the issue to either the template or ACF.

**Comment by MWDelaney** [comment]
This should be fixed. Thank you for your patience!
