### ISSUE TITLE
`resources/views/blocks` might not be created

### ISSUE THREAD

**Issue by TangRufus** [MWDelaney/sage-acf-gutenberg-blocks#3]
https://github.com/MWDelaney/sage-acf-gutenberg-blocks/blob/6eac68833bb12477b40086d831421c589b4cfc27/sage-acf-gutenberg-blocks.php#L32-L38

This might break on non-linux servers OR servers that enforce tight file permissions.

Suggest: Use [WP Filesystem API](https://codex.wordpress.org/Filesystem_API) and check double check directory is created.

**Comment by MWDelaney** [comment]
Or just rely on the user to create the directory, maybe?

**Comment by TangRufus** [comment]
Agree.

Going further, a better way might be let users to provide a list of file paths, i.e:
Current:

```
        // Get all templates in 'views/blocks'
        $dir = new \DirectoryIterator(\locate_template($template_directory));
        // Loop through found templates and set up data
        foreach ($dir as $fileinfo) {
            if (!$fileinfo->isDot()) {
              // Strip the file extension to get the slug
                $slug = str_replace('.blade.php', '', $fileinfo->getFilename());
                // Get header info from the found template file(s)
                $file_path = locate_template("views/blocks/${slug}.blade.php");
``` 

New (something like this):

```
$templates = apply_filters('xxxx', []);

     foreach ($templates as $template) {
                $file_path = locate_template($template);
```

---

This gives users flexibilities put balde file paths in other locations AND other packages to inject more paths.

**Comment by MWDelaney** [comment]
We'd still need to use the `DirectoryIterator` to get all the templates in the directory. Otherwise we'd need to inform the library of each template individually. I'll play with this a little...

**Comment by MWDelaney** [comment]
e4666a94b22b85bfe6bfcb7264b604a5b50565f1 should allow adding more block locations via filter.
